# Generated by Django 4.2.16 on 2024-09-22 06:07

from django.db import migrations, models
import django.utils.timezone
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('file_upload', django_cryptography.fields.encrypt(models.FileField(upload_to='files'))),
            ],
        ),
    ]
