# Generated by Django 4.2.16 on 2024-09-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_alter_fileupload_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
