# Generated by Django 4.2.16 on 2024-09-22 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_alter_fileupload_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
